<?php

/**
 * Implements hook_theme().
 */
function bits_entities_theme(){
    $theme = [];
    $theme['bits_entities_message'] = [
        'render element' => 'elements',
        'file' => 'bits_entities_message.page.inc',
        'template' => 'bits_entities_message',
    ];
    $theme['bits_entities_message_content_add_list'] = [
        'render element' => 'content',
        'variables' => ['content' => NULL],
        'file' => 'bits_entities_message.page.inc',
    ];
    return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function bits_entities_theme_suggestions_bits_entities_message(array $variables) {
    $suggestions = array();
    $entity = $variables['elements']['#bits_entities_message'];
    $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

    $suggestions[] = 'bits_entities_message__' . $sanitized_view_mode;
    $suggestions[] = 'bits_entities_message__' . $entity->bundle();
    $suggestions[] = 'bits_entities_message__' . $entity->bundle() . '__' . $sanitized_view_mode;
    $suggestions[] = 'bits_entities_message__' . $entity->id();
    $suggestions[] = 'bits_entities_message__' . $entity->id() . '__' . $sanitized_view_mode;
    return $suggestions;

}